export default {
    images: [
        {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/1.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['dummy', 'card12'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/2.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/3.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/4.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['dummy', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/5.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/6.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/7.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/8.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/9.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }, {
            cardTitle: 'Card Title',
            cardDir: '../../../assets/images/10.jpg',
            cardDes: 'Card Description',
            cardViewed: '44',
            cardLiked: '80',
            cardType: 'Card Type',
            cardTags: ['card1', 'card1'],
        }
    ],
};